src/lists.jl, test/gui.jl
This is similar to #126 but assumes the user will use mutable iters. I see that is how they are to use GtkTextIters and is the same as the gtk_ methods, so closer to the official documentation. Seems to me this is  just a bit more work but has the advantage of being more familiar and would be consistent with these methods if /when they are generated programmatically.
=> Pull request/d8fe3df2

src/basic_exports.jl, src/windows.jl
```jl
resp, firstname = input_dialog("Enter your first name, if you want to", "Julia", (("No thanks",0), ("OK",1)))
```
=> Add input_dialog

test/gui.jl
replaced exact assert with simple if test and warning.
=> replaced exact position test #187

src/lists.jl
=> Fixed path_at_pos problem

src/events.jl
=> fix parsing on 0.5

src/lists.jl, test/gui.jl
This empties the choices in a `ComboBoxText` so that you can repopulate it. I'd like to write a test, but I'm not quickly discovering how to iterate over the current items in the ComboBox. Any pointers?
=> Add `empty!(combobox)`

REQUIRE, src/GLib/GLib.jl, src/GLib/signals.jl, src/Gtk.jl, src/text.jl
Note that this introduces Compat.jl as a dependency.
=> Fix string, atsign-windows, and Base.(sym) deprecations

.travis.yml, REQUIRE
I disagree with the commit message of 0723b4dd0d3d7ca0d71e85181960cb9797f1c7ed, given how finicky BinDeps can be across different platforms.
=> add back osx travis

src/base.jl, src/gio.jl, src/gl_area.jl, src/text.jl, test/gui.jl
`visible` wasn't working with 0.5, it was an issue with `bool`. I changed all of them to `Bool`and added a test for `visible`.
=> change bool to Bool and add a test for visible

src/GLib/glist.jl, src/Gtk.jl, src/base.jl, src/gdk.jl, test/gui.jl, test/style_test.css
style improvements, a few typos, and preparation for https://github.com/JuliaLang/julia/pull/18754
=> updates and fixes

src/layout.jl, test/gui.jl
Added the missing title parameter in the Overlay constructor function in layouts.jl
=> Fixed Overlay constructor 

src/GLib/GLib.jl, src/GLib/glist.jl, src/GLib/gtype.jl, src/GLib/signals.jl, src/displays.jl, src/selectors.jl, test/gui.jl
update for v0.6 compat (except world change)
fix #190
probably fix #252 too
=> v0.6 compat + fixes

src/GLib/GLib.jl, src/GLib/MutableTypes.jl, src/GLib/gerror.jl, src/GLib/glist.jl, src/GLib/gtype.jl, src/GLib/gvalues.jl, src/GLib/signals.jl, src/Gtk.jl, src/base.jl, src/boxes.jl, src/builder.jl, src/buttons.jl, src/cairo.jl, src/container.jl, src/displays.jl, src/events.jl, src/gdk.jl, src/gio.jl, src/gl_area.jl, src/gtktypes.jl, src/input.jl, src/layout.jl, src/lists.jl, src/menus.jl, src/selectors.jl, src/text.jl, src/theme.jl, src/toolbar.jl, src/windows.jl
no functional changes, just making the whitespace formatting more consistent
=> whitespace

REQUIRE, src/GLib/glist.jl, test/gui.jl
take! requires minimum version of 0.9.5
ref https://github.com/JuliaGraphics/Gtk.jl/issues/263#issuecomment-281695222
=> Use isdefined and Compat instead of unspecific VERSION conditions

.travis.yml, REQUIRE, deps/ext.jl, deps/ext_glib.jl, gen/gtk_auto_gen.jl, src/GLib/GLib.jl, src/GLib/MutableTypes.jl, src/GLib/glist.jl, src/GLib/gtype.jl, src/GLib/gvalues.jl, src/GLib/signals.jl, src/Gtk.jl, src/compat_string.jl, src/container.jl, src/displays.jl, src/events.jl, src/gdk.jl, src/layout.jl, src/lists.jl, src/text.jl, test/glib.jl, test/gui.jl, test/runtests.jl
I'm leaving inline comments on a few changes I'm not sure about
=> drop julia 0.4 + fix errors and deprecations in 0.6

deps/build.jl
See Issue https://github.com/JuliaGraphics/Gtk.jl/issues/292
=> installing gnome icons in build.jl

docs/src/manual/workingCI.md
As follows from https://discourse.julialang.org/t/linux-travis-tries-and-fails-to-open-gtk-display/3179/6?u=yakir12
=> Documentation about travis

REQUIRE
am i correct in thinking this is cruft?
=> remove BaseTestNext from REQUIRE since it's not used anywhere

example/2048.jl
I think the package needs more examples, so here is one.
=> Add the game 2048 as an example.

docs/src/manual/filedialogs.md
Updates FileDialog documentation so that the examples work as expected.
=> Update FileFilter to GtkFileFilter and correct filter spacing in Docs

docs/src/manual/listtreeview.md
=> Remove Julia < 1.0 support from list filtering example.

deps/ext.jl, deps/ext_glib.jl
=> fix windows 10 issue

src/text.jl, test/gui.jl
There was a couple of issues with those, similar to the ones with `GtkTreeIter`. I also added a bunch of tests.
=> Fix GtkTextIter and add tests

src/long_exports.jl, src/long_leaf_exports.jl, src/misc.jl, src/short_exports.jl, src/text.jl
I added basic support for GtkEventBox and fixed a couple more bugs with GtkTextIter.
=> EventBox & TextIter fixes

src/GLib/GLib.jl, src/GLib/gvalues.jl, src/GLib/signals.jl, src/Gtk.jl, src/base.jl, src/basic_exports.jl, src/events.jl, src/selectors.jl, src/text.jl, src/windows.jl, test/glib.jl, test/gui.jl, test/runtests.jl, test/text.jl
I've moved `g_timeout_add`, `g_idle_add`, and a couple of other things that I had in GtkExtensions.jl. I still have other things in there (text and tree related mainly) but I need to review them.
I've added tests for most of it, but no documentation.
=> g_timeout_add and other things

gen/gtk_list_gen.jl, src/GLib/gtype.jl, src/GLib/signals.jl, src/lists.jl
Should address one of the issue in #400 
- fixed a cfunction and finalizer deprecation
=> GtkTreePath fixes

src/GLib/glist.jl, src/events.jl, src/lists.jl, test/gui.jl, test/runtests.jl, test/tree.jl
Following #400 I'm adding some tests for GtkTreeViews. 
I fixed a couple of issues but I'm getting segfaults on `selected_rows`, calling `gtk_tree_selection_get_selected_rows` seems to work but when I wrap the resulting pointer into ` GLib.GList` and try to do something with it (even show it) it crashes. We need to investigate further before we can merge this.
=> WIP. Adding tests for GtkTrees

src/lists.jl, test/list.jl, test/runtests.jl
This is a fix for issue #425 changed the Tuples to Unions, added tests for the new code.
=> Fixed an issue where v3 Text Combo Box item's didn't get their ID set.

src/GLib/signals.jl, test/glib.jl
Implementation suggested in https://github.com/JuliaGraphics/Gtk.jl/commit/17bfda1ea78a511cd39d58de56c09cadd93262fb#r34550618
@stevengj could you have a short look? I am by no means a cfunction expert.
@jonathanBieler: Do we want to keep the version with `user_data`?
=> add improved versions of idle_add and timeout_add 

src/GLib/gvalues.jl, src/basic_exports.jl, src/text.jl, test/glib.jl, test/gui.jl, test/runtests.jl, test/text.jl
I've added a couple of text related methods (search, place_cursor, select_range, selection_bounds, create_mark) and more options for the `skip` methods. 
I also added docstrings to the methods here, so we can start to move toward a more comprehensive documentation.
=> More text methods

deps/ext.jl, docs/src/doc/installation.md, gen/gtk_auto_gen.jl, src/Gtk.jl, src/application.jl, src/base.jl, src/buttons.jl, src/cairo.jl, src/gio.jl, src/gtktypes.jl, src/input.jl, src/interfaces.jl, src/layout.jl, src/lists.jl, src/selectors.jl, src/short_exports.jl, src/theme.jl, test/gui.jl, test/list.jl
Given that this package has not too much resources working on it, I think it is better to drop Gtk2 code.
=> remove Gtk2 code

test/gui.jl
=> Fix the Gtk tests on NewPkgEval

.drone.yml
They take a while, but tests are passing: https://cloud.drone.io/giordano/Gtk.jl/7.  You probably need to enable Drone for this repo: https://cloud.drone.io/
=> Add script for Drone CI

src/basic_exports.jl, src/text.jl, test/text.jl
Implements :
- `gtk_text_view_scroll_to_mark`
- `gtk_text_view_scroll_to_iter`
=> Add scroll_to method

src/GLib/signals.jl
=> Mitigate slowdown by decreasing the timeout

src/Gtk.jl
=> Get rid of the REPL slowdown on windows that was fixed by #741

example/calculator.jl
This is the Gtk.jl implementation of a simple calculator.
=> added new example

src/GLib/GLib.jl, src/precompile.jl
These give warnings on Julia 1.7 when the package is built.
=> Comment out non-functional precompiles

src/GLib/GLib.jl, src/GLib/signals.jl, src/base.jl, src/buttons.jl, src/displays.jl, src/input.jl, src/lists.jl, src/menus.jl, src/misc.jl, src/selectors.jl, src/text.jl, test/gui.jl, test/runtests.jl, test/text.jl, test/tree.jl
add tests for text and list and other widgets
remove unnecessary calls to g_type_init()
simplify toplevel()
fix allocation()
remove old links to gtk2 docs
fix selected_rows()
fix formatting issues in docstrings in text.jl
=> add tests, remove old links, fix a few issues

Project.toml, src/GLib/MutableTypes.jl, src/GLib/gvalues.jl
=> make sure value wrapped in mutable is not garbage collected

README.md
I sure wish someone had done this earlier!
=> Update README.md to steer users to Gtk4
