JuliaGraphics/Gtk.jl

src/Gtk.jl

Tested on 64 bit Linux. Reduced load time from 5.8 s to 1.1 s on Core i7, 3.4 GHz.

Automatically precompile Gtk.jl for newer versions of Julia.

---

.travis.yml
README.md
doc/more_signals.md
src/GLib/gtype.jl
src/GLib/signals.jl

Motivated by https://github.com/JuliaLang/Gtk.jl/issues/161#issuecomment-135972461

Improve documentation on signals

---

src/GLib/signals.jl

I had a callback that inadvertently returned an unrecognized object, and it took me longer to figure out how to debug it than it should have. This was the backtrace:
```jl
FATAL ERROR: Gtk state corrupted by error thrown in a callback:
ERROR: MethodError: `g_type` has no method matching g_type(::Type{GtkUtilities.Link.State{GtkUtilities.PanZoom.Interval{Float64}}})
in setindex! at /home/tim/.julia/v0.4/Gtk/src/GLib/gvalues.jl:64
in setindex! at /home/tim/.julia/v0.4/Gtk/src/GLib/gvalues.jl:42
in gvalue at /home/tim/.julia/v0.4/Gtk/src/GLib/gvalues.jl:13
in gvalue at /home/tim/.julia/v0.4/Gtk/src/GLib/gvalues.jl:18
in GClosureMarshal at /home/tim/.julia/v0.4/Gtk/src/GLib/signals.jl:98
ERROR (unhandled task failure): MethodError: `g_type` has no method matching …
```

Emit helpful information for invalid return type in callback

---

src/base.jl
src/basic_exports.jl
test/misc.jl
test/runtests.jl

Currently while developing a new application, it's easy to corrupt Gtk state by writing a callback that throws an error; when that happens, you have to quit julia and start all over again. This adds a convenience macro, `@guarded`, that can be applied to any function definition to prevent corruption.

Add atsign-guarded for creating callbacks that don't corrupt Gtk state

---

README.md
doc/more_signals.md
src/base.jl
test/misc.jl

This also:
- adds some hints about properly specifying the types
in signal handler for the Event argument.
- extends atsign-guarded to work with do-block functions

Add documentation for atsign-guarded, mouse handler

---

deps/build.jl

This combined with https://github.com/staticfloat/homebrew-juliadeps/pull/73 should fix https://github.com/JuliaGraphics/Immerse.jl/issues/11.

Set additional gdk-pixbuf env vars for Homebrew

---

src/events.jl

I'm not certain whether this `isinteractive` check is needed for typical use, but deleting it didn't seem to break the tests.

Fix userimg: don't check isinteractive in __init__ (fixes #198)

---

src/theme.jl
test/gui.jl
test/style_test.css

There was an extra type in the c function signature.

Fix CssProviderLeaf(filename="...")

---

src/lists.jl

In the GtkTreePath constructor the return type of gtk_tree_path_copy was Void but the function returns a pointer to GtkTreePath

fixed gtk_tree_path_copy return value type

---

src/GLib/GLib.jl
src/GLib/glist.jl
src/GLib/gtype.jl
src/GLib/gvalues.jl
src/GLib/signals.jl
src/Gtk.jl
src/buttons.jl
src/cairo.jl
src/compat_string.jl
src/displays.jl
src/events.jl
src/gtktypes.jl
src/lists.jl
src/selectors.jl
src/text.jl
src/theme.jl
src/windows.jl
test/gui.jl

Most of this is tedious, but there are a couple that might be worth a look:
- d9048f5506fd3b5b3c6f1fcd8614566db7c78591: I was lazy and didn't check whether there is a better way
- 11ae24d1228cc3cc254e4d385e60822a46786efc: is it weird this didn't cause an error before?
The one thing left to make this perfect :smile: on julia-0.5 would be to eliminate the overwritten function warnings in `gen/`.

The big julia-0.5 update

---

README.md
src/GLib/GLib.jl
src/GLib/gtype.jl
src/GLib/signals.jl
src/base.jl
src/gio.jl
test/gui.jl

this doesn't fix 161, it just moves the failure condition so that it
should be much less common and more avoidable

simplify sigatom code

---

deps/ext.jl
deps/ext_glib.jl
src/GLib/GLib.jl
src/GLib/gvalues.jl
src/GLib/signals.jl
src/gdk.jl
test/misc.jl

I didn't fix the `@static` deprecation. There's a fix here:
https://github.com/JuliaLang/Compat.jl/commit/f59536084236dfa0437601111a20aab4c82cfba8
I'm increasingly wondering about the wisdom of avoiding Compat.jl.

Make it easy to construct a dummy `GdkEventKey`, plus fix new deprecations

---

src/Gtk.jl

Implement the suggestion https://github.com/JuliaGraphics/Gtk.jl/pull/209#issuecomment-221935860
Will be necessary to conditionally implement things that have been introduced to Gtk during the version 3 cycle.

Generate libgtk_version during initialization

---

src/layout.jl
test/gui.jl

this complements the already existing `insert!` for grids with a corresponding `deleteat!`

added gtk_grid_remove_row/column convenience function

---

example/gl-area.jl
src/Gtk.jl
src/gl_area.jl
src/gtktypes.jl
src/layout.jl
src/long_exports.jl
src/long_leaf_exports.jl
src/short_exports.jl
src/short_leaf_exports.jl

GtkGLArea was introduced in Gtk3 as part of library.
Earlier, (Gtk2) it was a separate library.

Added GtkGLArea for Gtk3.

---

src/Gtk.jl

this is at least a partial fix for gtk2.  specifically it fixes the determination of `libgtk_version`.  i can now `using Gtk` on a linux box with gtk v2.24.23 without any problems.
on a second box though, with v2.18.9, i also have to modify `deps/build.jl` to include `libgtk-x11-2.0` as a dependency.  not sure why this isn't necessary on the first box.  this version of gtk is perhaps not worth supporting as `GtkSpinner` is in `Gtk.jl` and only present in `gtk` since v2.20.

fixed libgtk_version for gtk2

---

src/container.jl

looks correct @stevengj?
ref https://github.com/JuliaLang/julia/pull/17393#issuecomment-234122725

fix broken syntax on 0.5

---

.travis.yml
src/GLib/glist.jl

I'm going to tag a new release, since the current one fails on 0.5 and makes packages like ProfileView fail their tests.

Fix super->supertype deprecation warning

---

src/selectors.jl
test/gui.jl

This pull request is meant to fix the problem described in #247 
In the current version
```julia
@GtkFileFilter("*.txt")
```
will fail with a `MethodError` in julia 0.4.6
This also means that 
```julia
open_dialog("Open a File", GtkNullContainer(), ("*.txt",  ))
```
fails in julia 0.4 while using that constructor.
Until this problem is fixed file filtering in dialogs is impossible in julia 0.4

Fixed GtkFileFilter MethodError for ASCIIStrings in julia 0.4

---

REQUIRE
deps/build.jl
deps/ext.jl
gen/gi_gen_consts.jl
src/Gtk.jl
src/application.jl
src/base.jl
src/boxes.jl
src/buttons.jl
src/cairo.jl
src/gio.jl
src/gtktypes.jl
src/input.jl
src/interfaces.jl
src/layout.jl
src/lists.jl
src/selectors.jl
src/short_exports.jl
src/theme.jl
test/glib.jl
test/gui.jl
test/misc.jl
test/runtests.jl

this PR adds aliases for libgtk2 and libgdk2, which partially fixes https://github.com/JuliaGraphics/Gtk.jl/issues/194

better support for different versions of gtk

---

src/lists.jl

this by mistake called `select_all`

Fix typo in unselectall!

---

src/displays.jl

Update syntax on lines 275 and 277 to prevent warnings. GtkIconSize.(size)    cahnged to    getfield(GtkIconSize, size)

Update syntax to prevent warnings

---

src/events.jl

This was already possible using mouse button 1 (left click), this just adds the same functionality for the other mouse buttons.

Allow click-and-drag using mouse buttons 2 or 3

---

src/cairo.jl
src/events.jl
test/gui.jl
test/misc.jl

This stores the `id`s of the default mouse handlers so that they can be manipulated later. In particular, I want this for GtkReactive.jl, since I have my own Reactive-based handlers there.

Allow mouse handler signals to be disconnected

---

src/lists.jl

Just a small bugfix, it still used v0.3 ntuple.

Fix a bug in GtkTreeModel

---

src/GLib/gtype.jl
test/glib.jl

Discovered this ambiguity while looking at #311. This doesn't fix it, but I thought one might as well fix the ambiguity.
There's still one more involving GList.

Fix ambiguity in GLib convert methods

---

docs/src/manual/async.md
docs/src/manual/builder.md
docs/src/manual/canvas.md
docs/src/manual/combobox.md
docs/src/manual/customWidgets.md
docs/src/manual/gettingStarted.md
docs/src/manual/keyevents.md
docs/src/manual/layout.md
docs/src/manual/listtreeview.md
docs/src/manual/signals.md
docs/src/manual/textwidgets.md

As a new user to the package, I found a steady flow of deprecation warnings when running copy-pasta of the examples given in the docs. 
The warnings arise from [this commit](https://github.com/JuliaGraphics/Gtk.jl/commit/1a49e6bb7ff5b3daff8fab2f73b0fdbc18ba08d7), where `@Gtk...` is deprecated for `Gtk...` . 
This PR is so that the examples in the docs reflect the same.
Also included are a few typo fixes.

Fix deprecation warnings and typo corrections in docs

---

gen/gconsts3
gen/gi_gen_consts.jl
gen/gtk_auto_gen.jl
gen/gtk_consts_gen.jl
gen/gtk_get_set_gen.jl
gen/gtk_list_gen.jl

This is a fix for issue #319 , where autogen'd constants don't match values received from Gtk keyboard events. To be specific, GDK_KEY bindings in `gconsts3` with a value ending in `f` were missing the preceding `0` and following `f` from the binding value (i.e. 0x006f would appear as 0x06).
I initially attempted to run `gtk_auto_gen.jl` to generate the bindings, but ran into header path issues that caused the auto-generated `gconsts3` file to miss the key bindings. Therefore, a simple find-and-replace was done to correct the incorrect key bindings. I also made `gtk_auto_gen.jl` and other gen dependencies 0.6-compatible in the process. Please let me know if I should instead remove those changes and just leave the keybinding fixes.
NOTE: This is my first PR, and I probably totally messed …

Fixes #319, also improves autogen 0.6 compatibility

---

deps/build.jl

Running `Pkg.build("Gtk")` was failing on the line `Homebrew.add("gnome-icon-theme")`. Apparently the formula `gnome-icon-theme` was renamed to `adwaita-icon-theme` (see [this commit](https://github.com/Homebrew/homebrew-core/commit/0bcd2729c920a0e4c46a13f2d3f75b8a1889a8d8)).
After the proposed change everything works again.

Change 'gnome-icon-theme' to 'adwaita-icon-theme'

---

deps/build.jl

This should fix https://github.com/JuliaImages/ImageView.jl/issues/127 and #180. Not sure what's the best way to test whether this is working successfully since I had already fixed this error locally.

update gdk-pixbuf cache upon installation

---

docs/src/manual/builder.md
docs/src/manual/filedialogs.md
docs/src/manual/nonreplusage.md

Some of the examples in the documentation at [https://juliagraphics.github.io/Gtk.jl/latest/index.html](https://juliagraphics.github.io/Gtk.jl/latest/index.html) still used deprecated macros.

fixed some macro-related deprecation warnings in documentation

---

src/lists.jl
test/gui.jl

The same as #343, but with the requested test added.
Fixes #337 and closes #343.

Fix index_from_iter parsing wrongly

---

.travis.yml
REQUIRE
docs/make.jl
src/GLib/MutableTypes.jl
src/GLib/glist.jl
src/GLib/gtype.jl
src/Gtk.jl
src/container.jl
src/gdk.jl
src/text.jl

Julia 0.5 has been declared officially unmaintained, so [package updates won't be accepted if they support this version](https://github.com/JuliaLang/METADATA.jl/pull/12729). This led to JuliaLang/METADATA.jl#14843 getting rejected. This PR makes 0.6 the minimum required julia version and removes compat macros that aren't needed anymore.

Drop support for Julia 0.5

---

deps/build.jl

Resolves #289 
To verify that this works, I created a new Dockerfile based on [docker-library/julia](https://github.com/docker-library/julia/blob/06148bd09222645c2996f50094d76aeeb9ed4556/Dockerfile ) which you can find here: https://gist.github.com/rdeits/b92935c572f9d057d7121c904e2c8040 The dockerfile has no gtk packages pre-installed, but builds Gtk.jl successfully after this change. 
I've tested the Docker build on Ubuntu 14.04, 16.04, and 17.10 along with Debian Jessie.
If you'd like, I can set up the Docker build as an additional build on Travis so this will get tested in the future.

switch `build.jl` to use libgtk-3-dev from apt

---

docs/src/manual/textwidgets.md

* Missing newline.
* The `:text` property was set to `false`, instead of the `:editable` property, resulting in the editable label "FALSE".

Update section 'Text Widgets' of the documentation

---

docs/src/manual/builder.md

Only minor fixes here:
* Add missing quotes to the file path.
* The note on `Pkg.dir("MyPackage")` should maybe also be modified to reflect the fact that it is deprecated in 1.0. I am not sure which replacement is best here, though. I tend to use `@__DIR__` a lot, but the deprecation warning recommends using `joinpath(dirname(pathof(MyPackage)), "..", paths...)` instead. I have *not* changed the note.

Update section 'Builder and Glade' of documentation

---

docs/src/manual/layout.md

Tested on Julia 1.0.
The link to the image on line 55 is still broken. I don't know how to fix it.

Fix broken examples in Layout section

---

docs/src/manual/signals.md

Add missing `Gtk`'s in `GtkFunctionName(...)`.

Fix broken examples in section 'Signals and Callbacks'

---

docs/src/manual/builder.md

Suggest using the `@__DIR__` macro instead, as mentioned in #373.

Documentation: add note about deprecation of Pkg.dir() in Julia 1.0

---

docs/src/manual/listtreeview.md

* Add missing `Gtk`'s
* Remove unnecessary `enumerate` on line 83.
* Fix typos.
* Fix broken example in lines 101:103. For some reason I need to use 1-based indices to make all three columns reorderable. Not sure why this is the case here and not elsewhere since I am not very familiar with GTK.
* `contains(a, b)` -> `occursin(b, a)` in Julia 1.0.

Update section 'List and Tree Widgets'

---

example/2048.jl
example/gl-area.jl

I tried to fix the examples to run in Julia 0.7, 1.0.
Some remaining annoying things.
* 2048.jl
-  Got the following message on`info_dialog`
```Gtk-Message: 13:40:21.376: GtkDialog mapped without a transient parent. This is discouraged.```
* gl-area.jl
- Displayed the text `Not implemented on OS X` on GLArea in my mac OSX. I can't find where it has to be.

Fix examples

---

deps/build.jl

`Pkg` now has to be explicitly imported to be used.

Fix build.jl on Windows

---

src/GLib/GLib.jl
src/GLib/gerror.jl
src/GLib/gtype.jl
src/GLib/gvalues.jl
src/Gtk.jl
src/gdk.jl
src/gtktypes.jl

Fixes #367. Sorta messy but I didn't want to change things around too much. Still needs a test. Maybe `cm` needs a better name?

Change `curr_module` to `__module__` (or `@__MODULE__` when appropriate)

---

src/events.jl

Convenience function useful for things like stepping through procedural code one button click at a time, blocking a component until something specific happens, or keeping Julia from exiting when in interactive mode.
In the last (very common) usecase, it basically just wraps the snippet inside the if block at http://juliagraphics.github.io/Gtk.jl/latest/manual/nonreplusage.html into a function.

Add waitforsignal(widget,signal) function

---

src/displays.jl

Fixes bug with (seemingly) random alpha channel on alpha enabled Pixbufs.
Makes convert(::RGBA, ::Unsigned) work for Pixbuf data manipulation.

Added Alpha to RGBA struct constructor

---

src/lists.jl

`pop!(::GtkListStoreLeaf)` uses `length(::GtkListStore)` which currently returns an `Int32` instead of an `Int`.
It then calls `deleteat!(...)` which expects an index of type `Int` (thus failing to match signature when called with `Int32`).
I am pretty certain that we don't want to "loosen" `deleteat!(...)` to take in `Integer` types... so I instead ensure the output of `length()` is of type `Int`.

Make length() return Int instead of Int32.

---

src/GLib/GLib.jl
src/GLib/signals.jl
src/base.jl
src/basic_exports.jl
test/glib.jl

This is a macro that simplifies usage of `g_idle_add` a little bit. This may now be a drop-in replacement for `@sigatom`. Not sure if we actually still need that.

add macro idle_add

---

.travis.yml
docs/Project.toml
docs/make.jl

cleanup travis script+docu

---

src/events.jl

After the second time wasting quite a bit of time to debug why everything is suddenly sluggish, until I noticed that some unexpected third party library was loading in Gtk, I come to the conclusion that we really need this warning.

Usage of Gtk on windows needs a warning

---

Project.toml
docs/Project.toml
test/gui.jl

In preparation for https://github.com/JuliaGraphics/Graphics.jl/pull/16. It's better if the `set_coordinates` test gets done here since this the top of the dependency hierarchy. I have a suspicion it will fail based on https://github.com/JuliaGizmos/GtkReactive.jl/pull/91 (and that this is a regression), but we will see.

Support Graphics 1.0 and test set_coordinates (+Documenter bounds)

---

src/GLib/signals.jl
src/Gtk.jl
src/basic_exports.jl
test/gui.jl

This can be useful for preventing Gtk error messages specifying that a widget lacks the given handler. [This Reactive.jl callback](https://github.com/JuliaGizmos/GtkReactive.jl/blob/f8b985bdfdb80da3cb46002f6e36c553eb1e9e58/src/widgets.jl#L51-L57) sometimes tries to fire after the widget has been cleaned up.

Support signal_handler_is_connected

---

src/Gtk.jl

Can we please, please leave this warning? Debugging this problem can waste days of frustrating debugging, even for experienced Julia developers, as you can see here: https://discourse.julialang.org/t/serious-issue-julia-language-keyboard-lag-typing-very-slow/32081/23
A package, which turns calculating a simple spectrogram from 0.02s to 1.7s (it's actually not as bad anymore, it was 50s before 1.1.0) just by using it anywhere in the dependency stack definitely needs to be warned about.
```Julia
(v1.3) pkg> st Gtk
Status `C:\Users\sdani\.julia\environments\v1.3\Project.toml`
[4c0ca9eb] Gtk v1.1.0
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
OS: Windows (x86_64-w64-mingw32)
CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
WORD_SIZE: 64
LIBM: …
```

Warn on windows

---

src/text.jl

This is already the default definition for `!=` and defining it leads to invalidations.

remove unnecessary != definition

---

src/GLib/GLib.jl
src/events.jl

This seems to work well enough for now as a workaround; ImageView.jl works at least. Would be good to try some more Gtk apps to confirm whether it works. I wanted to to just un-break 1.5, and we can work on a redesign later.

fix for julia v1.5; `jl_function_ptr` was removed

---

src/GLib/GLib.jl
src/GLib/MutableTypes.jl
src/Gtk.jl

This, together with the same change in GtkReactive and ProfileView, shaves about 200ms off the first call to ProfileView.view(). Not bad, but not a game-changer either.
xref https://github.com/JuliaLang/julia/pull/32705#issuecomment-685155916

Set optlevel to 1

---

src/lists.jl
test/gui.jl

Closes #514 
Adds `delete!` and `insert!` for manipulating TreeViewColumns in a TreeView.
I went with `delete!` over the requested `deleteat!` since the user is providing the object(s) to be removed, rather than the index of the object to be removed.
I did however note that [ListStore](https://github.com/JuliaGraphics/Gtk.jl/blob/master/src/lists.jl#L168) does provide both names, should that be done here too?

Add delete and insert for TreeView

---

src/buttons.jl
src/gdk.jl
src/gtktypes.jl
src/long_exports.jl
src/long_leaf_exports.jl
src/selectors.jl
src/short_exports.jl
src/short_leaf_exports.jl
test/gui.jl

Relevant Gtk docs: [GdkRGBA](https://developer.gnome.org/gdk3/stable/gdk3-RGBA-Colors.html), [GtkColorChooserDialog](https://developer.gnome.org/gtk3/stable/GtkColorChooserDialog.html), [GtkColorButton](https://developer.gnome.org/gtk3/stable/GtkColorButton.html).
Partially replaces #244 (and by extension partially closes #243).
Also adds `color_chooser_dialog` convenience function for displaying a GtkColorChooserDialog similarly to `open_dialog`/`save_dialog`.
`color_chooser_dialog`  returns `nothing` if no color is selected (cancel or close button pressed) to distinguish from just selecting the default color.
GtkColorChooserDialog is still subject to #530, so it may be worth also adding the deprecated GtkColorSelectionDialog, which seems to work just fine.
I also took a look at the …

Add GdkRGBA, ColorChooserDialog, ColorButton

---

src/theme.jl

According to https://github.com/JuliaGraphics/Gtk.jl/issues/526#issuecomment-702083869
I merely replaced the function name here to get things started. I could not properly test this myself because Gtk.jl master is not working for my projects right now. Is this really all there is to it?

Replacing gtk_css_provider_get_default by gtk_css_provider_new

---

.github/workflows/CompatHelper.yml

This allows CI to run in pull requests opened by CompatHelper.
Ref https://github.com/JuliaGraphics/Gtk.jl/pull/544#issuecomment-751408042.  CC: @timholy.

Use DOCUMENTER_KEY for CompatHelper

---

src/Gtk.jl

With the new BB binaries the window decorations show correctly without setting GTK_CSD=1
close #547 
@ping NeoKat75: I cannot test this, have you tested it with exactly this change?

Fix #547 and revert #355

---

src/GLib/GLib.jl
src/Gtk.jl
src/precompile.jl

These were found via the new capabilities in the soon-to-be-released SnoopCompile. Not a big change but you can see the time savings in the comment after each line.

Slightly expand precompiles

---

src/GLib/signals.jl
src/precompile.jl

These were identified similarly to #549

Yet more precompiles

---

src/text.jl
test/text.jl

It seems that `v[:buffer, GtkTextBuffer]` was intended to be provided
by automated mechanisms, but it doesn't currently work.
This provides it manually.

Provide the stated GtkTextView interface

---

src/GLib/gtype.jl

Debugged with @vtjnash . The MWE in the issue works with this, but would be good to get some more testing.

fix #562, bug in reviving objects when WeakRefs are cleared earlier

---

.drone.jsonnet
.drone.yml
.github/workflows/ci.yml

I'm using this PR also to test that the package works with GTK 3.24.29, but will remove that change afterwards

[CI] Remove redundant version of Julia from matrix

---

src/gdk.jl
src/lists.jl
src/text.jl
src/theme.jl

I've added the bindings for a couple of functions that are not in GAccessor. I think that's the last batch of methods I had in my GtkExtensions package.
I haven't had the time to add tests so I didn't exported the methods (not sure if we want to export everything all the time), but I think it's still good to have those in here. I'll add some if I have the opportunity. I also fixed a couple of formatting issues.

Added miscellaneous text and window related bindings

---

src/GLib/signals.jl
src/text.jl

Fix incorrect method leading to silent exceptions in signal handlers

---

docs/src/manual/layout.md

showall(win) is needed after push!() hbox, cancel, and ok. Otherwise the new GtkButtonBox hbox will not show, nor will the cancel and ok GtkButton's.

showall(win) is needed after push!() hbox, cancel, and ok

---

src/lists.jl
test/gui.jl

Fixes an invalid read in a test found using valgrind. The test assumes that the iter is invalidated by deleteat!(), but according to the GTK docs that should only happen if the iter points to the last row (which it doesn't). Plus the iter is passed in as an immutable struct, so it doesn't seem like it could change. Anyway, the gtk_list_store_iter_is_valid() call attempts to access the row that was just deleted. I added a test that verifies the row was deleted. Also fixes a typo in the ListStore code.

fix a test of List view

---

Project.toml
src/GLib/signals.jl

As a consequence of the forced specialization on the `RT` argument
of `signal_emit` in #552, the compiler now knows whether
`RT === Nothing`. In that case, it also knows that
`return_value` will not be used, so it is free to be garbage-collected.
When that happens, it triggers segfaults. EDIT: actually, that can't
be correct, because it doesn't create them when `RT===Nothing`.
So probably #552 didn't trigger this.
This puts both potential `GValue`-arguments inside a `GC.@preserve`
to prevent garbage collection. Fixes #581.
A reproducer of the crash is with GtkObservables:
```sh
/some/path/GtkObservables$ julia --check-bounds=yes --color=yes --depwarn=yes --inline=yes --project=@. -e 'import Pkg; Pkg.test(; coverage=true)'
```
but that is obviously difficult to convert into a test. I've …

Preserve GValues from GC (fixes #581)

---

src/GLib/GLib.jl
src/GLib/glist.jl
test/glist.jl
test/runtests.jl

Adds tests for GList and fixes a couple of bugs. Also removes some array interface declarations that don't seem to be necessary.
* In the string code, rename unsafe_copy! to unsafe_copyto!.
* Explicitly convert a number to a pointer for storing numbers in a GList.
* Add a constructor for GSList for testing purposes.
* Remove a few standard array interface declarations that don't seem necessary since they are the default.

add tests for GList, fix a few things related to GList

---

src/GLib/glist.jl
src/layout.jl
test/glist.jl
test/gui.jl

Fixes a problem with finalizing GLists, appending GLists, and iterating over GSList. Also fixes a few issues in layout.jl found while adding tests.

add more tests, fix a few issues with GList, GtkGrid, GtkNotebook, GtkOverlay

---

src/GLib/GLib.jl
src/GLib/signals.jl
src/Gtk.jl
src/base.jl
src/windows.jl

As reported in https://github.com/JuliaGraphics/Gtk.jl/issues/503 & https://github.com/JuliaLang/julia/issues/35552 loading Gtk in a julia session basically ruins the performance of the session from there-on out, especially threading.
Fixing the core issue appears to be intrinsic to how julia runs threads, and might take a while to fix(?)
So... this PR:
- Introduces `Gtk.enable_eventloop(b::Bool)` for start/stopping the GLib event loop, which prevents blocking other julia tasks/threads
- By default starts Gtk in idle state with no event loop
- The event loop is then started with any call to `show` or `showall` so that rendering always starts when something is shown
- Then stops the eventloop when all `show`-ed widgets have been destroyed
- Previous behavior can be regained via setting env …

Automatic event loop start/stop when not showing anything

---

src/base.jl

Specifically, calling out how it interacts with `visible` property and how `no_show_all` can be used to prevent that.
Addresses #609

Add documentation to showall

---

src/Gtk.jl
src/base.jl

Fixes #610
The fix indicated to work for @Vexatos https://github.com/JuliaGraphics/Gtk.jl/issues/610#issuecomment-1013760658
I'm not aware of this needing to be done outside of Windows, so decided to be conservative.
Also fixes an issue on MacOS where the window doesn't always close and freezes. 
It seems like there's a sequencing bug on MacOS, as it's pretty normal to call `quit_main` on `:destroy`
The async wait just gives some time for the window to finish closing.

Add a yield for windows (fix #610). Fix window not finishing close on MacOS

---

src/Gtk.jl
test/misc.jl

A do-block syntax like this is helpful for running functions where you explicitly don't want the eventloop running.
```
pause_eventloop() do
foo()
end
```

Add pause_eventloop for do-block syntax

---

README.md

old link 404: https://developer.gnome.org/gtk/stable

Update Gtk doc link

---

docs/src/doc/more_signals.md
docs/src/manual/signals.md
docs/src/manual/textwidgets.md
src/Gtk.jl
src/builder.jl
src/displays.jl
test/gui.jl
test/test.glade

Fixes iterating over GtkBuilder, a GtkStatusbar method, and an argument type in gtk_init_with_args. Also fixes links in docs.

add more tests, fix links in docs

---

src/container.jl

Found `GtkButton`s were not supported to `deleteat!` before.
Now add it.

Support `deleteat!` for all `GtkContainer`s

---

src/GLib/signals.jl

Might fix https://github.com/JuliaGraphics/Gtk.jl/issues/503
Closes https://github.com/JuliaLang/julia/issues/35552

Disable uv_backend_fd integration

---

docs/src/manual/keyevents.md

This PR adds an example of capturing key release events, to augment the previous key press example.
This particular example is motivated by the use case of using a computer keyboard
like a piano keyboard where you want to know the duration the key was pressed,
but surely there are other uses given that GTK does support key release events.

Document "`key-release-event"`

---

docs/src/index.md

`GtkObservables` is in JuliaGizmos rather than `JuliaGraphics` so having this link in the readme may aid discovery.  I for one did not know about it until seeing this:
https://github.com/JuliaGraphics/Gtk.jl/pull/638#issuecomment-1083300336

Add link to `GtkObservables`

---

.github/workflows/ci.yml

This adds `parallel: true`, which is mandatory if you are using a build matrix. (This was also supported with the old uploader via environment variables, but this also switches to the official uploader).
n.b. this previously has always failed with 'ERROR: Coveralls submission requires a COVERALLS_TOKEN environment variable'

add coveralls flag-name

---

docs/src/manual/listtreeview.md

Age is in 2nd column instead of 1st.
Console output when selecting a row, before fix:
`Name: Peter Age: Peter`
After this fix:
`Name: Peter Age: 20`

Tiny fix in documentation code snippet about GtkTreeModelFilter

---

src/Gtk.jl
test/runtests.jl

This prevents Julia from crashing.
Also remove redundant tests that I introduced.

fail in __init__() with error if Gtk4 was previously imported

---

docs/src/manual/canvas.md

Julia's standard-library documentation does not include information on graphics like this.

Remove misleading reference

---

docs/src/manual/async.md

Update async.md for 1.0 and Threading

---

docs/src/manual/signals.md

I'm assuming that these restrictions are fixed now that the PR has merged, but I don't know for sure.
Closes #637

Remove outdated warning in docs

---

docs/src/manual/keyevents.md

Two sequential releases resulted in an error because the first set `time0` to `notihing` and the second tried to use `time0`.
Before:
```
julia> You pressed key 97 which is 'a'.
repeating key 115
repeating key 100
You released key 97 after time 121 msec.
┌ Warning: Executing #51:
└ @ Gtk.GLib ~/.julia/packages/Gtk/OyCvN/src/GLib/signals.jl:106
ERROR: MethodError: no method matching -(┌ Warning: Executing #51:
└ @ Gtk.GLib ~/.julia/packages/Gtk/OyCvN/src/GLib/signals.jl:106
::ERROR: UInt32MethodError: , no method matching ::-Nothing()::
Closest candidates are:
-(::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) at int.jl:85
-(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:86
-(::Union{UInt16, …
```

Handle multiple keypresses in example

---

src/container.jl
src/layout.jl
test/gui.jl

Also provide useful errors in a couple of GtkGrid methods.
Fixes #669

avoid GList in empty!(c::GtkContainer)
